const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "united states": "US",
  usa: "US",
  us: "US",
  america: "US",
  "united states of america": "US",
  "united kingdom": "GB",
  uk: "GB",
  britain: "GB",
  "great britain": "GB",
  england: "GB",
  russia: "RU",
  "russian federation": "RU",
  "united arab emirates": "AE",
  uae: "AE",
  "united arab emirate": "AE",
  "iran uae": "AE",
  ukraine: "UA",
  ethiopia: "ET",
  eritrea: "ER",
  sudan: "SD",
  "south sudan": "SS",
  djibouti: "DJ",
  somalia: "SO",
  kenya: "KE",
  uganda: "UG",
  rwanda: "RW",
  burundi: "BI",
  tanzania: "TZ",
  "united republic of tanzania": "TZ",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  drc: "CD",
  "congo kinshasa": "CD",
  "republic of the congo": "CG",
  "congo brazzaville": "CG",
  congo: "CG",
  gabon: "GA",
  "equatorial guinea": "GQ",
  cameroon: "CM",
  "central african republic": "CF",
  chad: "TD",
  nigeria: "NG",
  niger: "NE",
  mali: "ML",
  mauritania: "MR",
  senegal: "SN",
  gambia: "GM",
  guinea: "GN",
  "guinea bissau": "GW",
  "sierra leone": "SL",
  liberia: "LR",
  "cote d ivoire": "CI",
  "ivory coast": "CI",
  ghana: "GH",
  togo: "TG",
  benin: "BJ",
  "burkina faso": "BF",
  algeria: "DZ",
  tunisia: "TN",
  libya: "LY",
  morocco: "MA",
  "western sahara": "EH",
  angola: "AO",
  namibia: "NA",
  botswana: "BW",
  zambia: "ZM",
  zimbabwe: "ZW",
  mozambique: "MZ",
  malawi: "MW",
  madagascar: "MG",
  "south africa": "ZA",
  lesotho: "LS",
  eswatini: "SZ",
  swaziland: "SZ",
  comoros: "KM",
  seychelles: "SC",
  mauritius: "MU",
  "cape verde": "CV",
  "cabo verde": "CV",
  argentina: "AR",
  bolivia: "BO",
  brazil: "BR",
  chile: "CL",
  colombia: "CO",
  ecuador: "EC",
  guyana: "GY",
  paraguay: "PY",
  peru: "PE",
  suriname: "SR",
  uruguay: "UY",
  venezuela: "VE",
  "french guiana": "GF",
  austria: "AT",
  belgium: "BE",
  bulgaria: "BG",
  croatia: "HR",
  cyprus: "CY",
  czechia: "CZ",
  "czech republic": "CZ",
  denmark: "DK",
  estonia: "EE",
  finland: "FI",
  france: "FR",
  germany: "DE",
  greece: "GR",
  hungary: "HU",
  iceland: "IS",
  ireland: "IE",
  italy: "IT",
  latvia: "LV",
  lithuania: "LT",
  luxembourg: "LU",
  malta: "MT",
  moldova: "MD",
  montenegro: "ME",
  netherlands: "NL",
  norway: "NO",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  belarus: "BY",
  kosovo: "XK",
  "north macedonia": "MK",
  albania: "AL",
  bosnia: "BA",
  "bosnia and herzegovina": "BA",
  australia: "AU",
  "new zealand": "NZ",
  "papua new guinea": "PG",
  fiji: "FJ",
  samoa: "WS",
  tonga: "TO",
  vanuatu: "VU",
  "solomon islands": "SB",
  "new caledonia": "NC",
  israel: "IL",
  palestine: "PS",
  iran: "IR",
  iraq: "IQ",
  syria: "SY",
  yemen: "YE",
  lebanon: "LB",
  jordan: "JO",
  egypt: "EG",
  saudi: "SA",
  "saudi arabia": "SA",
  turkey: "TR",
  "turkiye": "TR",
  china: "CN",
  taiwan: "TW",
  india: "IN",
  pakistan: "PK",
  afghanistan: "AF",
  myanmar: "MM",
  armenia: "AM",
  azerbaijan: "AZ",
  georgia: "GE",
};

const COUNTRY_NAME_LABELS: Record<string, string> = {
  usa: "United States",
  us: "United States",
  "united states of america": "United States",
  uk: "United Kingdom",
  britain: "United Kingdom",
  "great britain": "United Kingdom",
  england: "United Kingdom",
  "russian federation": "Russia",
  drc: "Democratic Republic of the Congo",
  "dr congo": "Democratic Republic of the Congo",
  "congo kinshasa": "Democratic Republic of the Congo",
  "congo brazzaville": "Republic of the Congo",
  "ivory coast": "Cote d'Ivoire",
  "cote d ivoire": "Cote d'Ivoire",
  "cape verde": "Cabo Verde",
  "czech republic": "Czechia",
  bosnia: "Bosnia and Herzegovina",
  uae: "United Arab Emirates",
  "united arab emirate": "United Arab Emirates",
  "iran uae": "United Arab Emirates",
  turkiye: "Turkey",
};

const STANDARD_COUNTRY_NAME_TO_CODE: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  andorra: "AD",
  angola: "AO",
  "antigua and barbuda": "AG",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  bangladesh: "BD",
  barbados: "BB",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  benin: "BJ",
  bhutan: "BT",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  bosnia: "BA",
  botswana: "BW",
  brazil: "BR",
  brunei: "BN",
  "brunei darussalam": "BN",
  bulgaria: "BG",
  "burkina faso": "BF",
  burundi: "BI",
  "cabo verde": "CV",
  "cape verde": "CV",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  "central african republic": "CF",
  chad: "TD",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  comoros: "KM",
  congo: "CG",
  "republic of the congo": "CG",
  "congo brazzaville": "CG",
  "democratic republic of the congo": "CD",
  drc: "CD",
  "dr congo": "CD",
  "congo kinshasa": "CD",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  czechia: "CZ",
  "czech republic": "CZ",
  denmark: "DK",
  djibouti: "DJ",
  dominica: "DM",
  "dominican republic": "DO",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  estonia: "EE",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  gabon: "GA",
  gambia: "GM",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  grenada: "GD",
  guatemala: "GT",
  guinea: "GN",
  "guinea bissau": "GW",
  guyana: "GY",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kiribati: "KI",
  kosovo: "XK",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  "lao pdr": "LA",
  latvia: "LV",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  "marshall islands": "MH",
  mauritania: "MR",
  mauritius: "MU",
  mexico: "MX",
  micronesia: "FM",
  moldova: "MD",
  monaco: "MC",
  mongolia: "MN",
  montenegro: "ME",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  namibia: "NA",
  nauru: "NR",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  "north korea": "KP",
  "south korea": "KR",
  "north macedonia": "MK",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  palau: "PW",
  palestine: "PS",
  panama: "PA",
  "papua new guinea": "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  rwanda: "RW",
  "saint kitts and nevis": "KN",
  "st kitts and nevis": "KN",
  "saint lucia": "LC",
  "st lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "st vincent and the grenadines": "VC",
  samoa: "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "sao tome & principe": "ST",
  "saudi arabia": "SA",
  senegal: "SN",
  serbia: "RS",
  seychelles: "SC",
  "sierra leone": "SL",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  "solomon islands": "SB",
  somalia: "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  spain: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  suriname: "SR",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  taiwan: "TW",
  tajikistan: "TJ",
  tanzania: "TZ",
  thailand: "TH",
  timor: "TL",
  "timor leste": "TL",
  togo: "TG",
  tonga: "TO",
  "trinidad and tobago": "TT",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  turkmenistan: "TM",
  tuvalu: "TV",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  britain: "GB",
  "united states": "US",
  usa: "US",
  us: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  venezuela: "VE",
  vietnam: "VN",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
  "central europe": "EU",
  "european union": "EU",
};

function normalizeCountry(value: string) {
  return value
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function toTitleCase(value: string) {
  return value.replace(/\b\w/g, (char) => char.toUpperCase());
}

export function getCountryDisplay(country: string) {
  const normalized = normalizeCountry(country);
  const displayName =
    COUNTRY_NAME_LABELS[normalized] ?? toTitleCase(normalized || country);
  const code =
    COUNTRY_NAME_TO_CODE[normalized] ??
    STANDARD_COUNTRY_NAME_TO_CODE[normalized] ??
    (normalized.length === 2 ? normalized.toUpperCase() : undefined);
  return {
    name: displayName,
    code,
  };
}

export function getCountryFlagEmoji(country: string) {
  const { code } = getCountryDisplay(country);
  if (!code || !/^[A-Z]{2}$/.test(code)) {
    return "🏳️";
  }
  return String.fromCodePoint(
    127397 + code.charCodeAt(0),
    127397 + code.charCodeAt(1),
  );
}

export function getCountryFlagPngUrl(country: string) {
  const { code } = getCountryDisplay(country);
  if (!code) {
    return null;
  }
  return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
}
